/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyneex.att.departments;

import com.xyneex.att.util.WindowsSetter;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Jevison7x
 */
public class CreateNewDepartment extends JDialog
{
    SelectDepartmentFrame parentFrame;

    /**
     * Creates new form CreateNewDepartment
     */
    public CreateNewDepartment(SelectDepartmentFrame parent, boolean modal)
    {
        super(parent, modal);
        parentFrame = parent;
        this.initComponents();
        this.centralizeWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleLbl = new javax.swing.JLabel();
        universityNameLbl = new javax.swing.JLabel();
        semesterLbl = new javax.swing.JLabel();
        deptNameLbl = new javax.swing.JLabel();
        sessionLbl = new javax.swing.JLabel();
        timeTableOfficerLbl = new javax.swing.JLabel();
        universityNameTF = new javax.swing.JTextField();
        semesterCB = new javax.swing.JComboBox();
        sessionCB = new javax.swing.JComboBox();
        deptNameTF = new javax.swing.JTextField();
        timeTableOfficerTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Create_new_pencil_button_32.png"))); // NOI18N
        titleLbl.setText("Create New Department");

        universityNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        universityNameLbl.setText("University Name:");
        universityNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        semesterLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        semesterLbl.setText("Set Semester:");
        semesterLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        deptNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deptNameLbl.setText("Department Name:");
        deptNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        sessionLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sessionLbl.setText("Session:");
        sessionLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        timeTableOfficerLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeTableOfficerLbl.setText("Time Table Officer:");
        timeTableOfficerLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        semesterCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIRST SEMESTER", "SECOND SEMESTER" }));

        sessionCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010/2011", "2011/2012", "2012/2013", "2013/2014", "2014/2015", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", "2025/2026", "2026/2027", "2027/2028", "2028/2029", "2029/2030", "2030/2031", "2031/2032", "2032/2033", "2033/2034", "2034/2035", "2035/2036", "2036/2037", "2037/2038", "2038/2039", "2039/2040", "2040/2041", "2041/2042", "2042/2043", "2043/2044", "2044/2045", "2045/2046", "2046/2047", "2047/2048", "2048/2049", "2049/2050" }));

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Save_Disk_32.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Cancel_button_32.png"))); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptNameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeTableOfficerLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(universityNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semesterLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sessionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semesterCB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(universityNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(deptNameTF)
                            .addComponent(timeTableOfficerTF))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addGap(72, 72, 72))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, saveBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universityNameLbl)
                    .addComponent(universityNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterLbl)
                    .addComponent(semesterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionLbl)
                    .addComponent(sessionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptNameLbl)
                    .addComponent(deptNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTableOfficerLbl)
                    .addComponent(timeTableOfficerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelBtn, saveBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelBtnActionPerformed
    {//GEN-HEADEREND:event_cancelBtnActionPerformed
        if(evt.getSource() == this.cancelBtn)
            this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveBtnActionPerformed
    {//GEN-HEADEREND:event_saveBtnActionPerformed
        if(evt.getSource() == this.saveBtn)
        {
            String universityName = this.universityNameTF.getText();
            String semester = this.semesterCB.getSelectedItem().toString();
            String session = this.sessionCB.getSelectedItem().toString();
            String departmentName = this.deptNameTF.getText();
            String timeTableOfficer = this.timeTableOfficerTF.getText();
            Department department = new Department();
            department.setUniversityName(universityName);
            department.setSemester(semester);
            department.setSession(session);
            department.setDepartmentName(departmentName);
            department.setTimeTableOfficer(timeTableOfficer);
            try
            {
                boolean created = DepartmentDAO.createNewDepartment(department);
                if(created)
                {
                    parentFrame.addNewDepartmentToComboBox(department);
                    JOptionPane.showMessageDialog(this, "The new Department was added successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
            catch(SQLException xcp)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "There was a database error! " + xcp.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void centralizeWindow()
    {
        WindowsSetter.centralizeWindow(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel deptNameLbl;
    private javax.swing.JTextField deptNameTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox semesterCB;
    private javax.swing.JLabel semesterLbl;
    private javax.swing.JComboBox sessionCB;
    private javax.swing.JLabel sessionLbl;
    private javax.swing.JLabel timeTableOfficerLbl;
    private javax.swing.JTextField timeTableOfficerTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel universityNameLbl;
    private javax.swing.JTextField universityNameTF;
    // End of variables declaration//GEN-END:variables

}
