/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyneex.att.departments;

import com.xyneex.att.MainFrame;
import com.xyneex.att.database.DataBaseDAO;
import com.xyneex.att.database.ResourceManager;
import com.xyneex.att.util.WindowsSetter;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jevison7x
 */
public class SelectDepartmentFrame extends javax.swing.JFrame
{
    private final ResourceManager resource = new ResourceManager();

    private Department[] departments;

    /**
     * Creates new form SelectDepartmentFrame
     *
     * @throws java.sql.SQLException
     */
    public SelectDepartmentFrame() throws SQLException
    {
        DataBaseDAO dbdao = new DataBaseDAO();
        List<Department> deptList = DepartmentDAO.getDepartments();
        Department[] deptArr = new Department[deptList.size()];
        departments = deptList.toArray(deptArr);
        this.setDefaultLookAndFeel();
        this.initComponents();
        this.centralizeWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        deptIconLbl = new javax.swing.JLabel();
        selectDeptLbl = new javax.swing.JLabel();
        selectLbl = new javax.swing.JLabel();
        deptComboBox = new javax.swing.JComboBox();
        proceedBtn = new javax.swing.JButton();
        createNewDeptBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deptIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Window_with_side_bar_selection_32.png"))); // NOI18N

        selectDeptLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectDeptLbl.setForeground(new java.awt.Color(0, 102, 0));
        selectDeptLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectDeptLbl.setText("Select a Department");

        selectLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectLbl.setText("Select a Department:");

        deptComboBox.setModel(new javax.swing.DefaultComboBoxModel(departments));

        proceedBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proceedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/next_button_32.png"))); // NOI18N
        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                proceedBtnActionPerformed(evt);
            }
        });

        createNewDeptBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createNewDeptBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Create_new_pencil_button_32.png"))); // NOI18N
        createNewDeptBtn.setText("Create New Department");
        createNewDeptBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createNewDeptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(createNewDeptBtn)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deptIconLbl)
                    .addComponent(selectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deptComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deptIconLbl)
                    .addComponent(selectDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLbl)
                    .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createNewDeptBtn))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createNewDeptBtn, proceedBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proceedBtnActionPerformed
    {//GEN-HEADEREND:event_proceedBtnActionPerformed
        if(evt.getSource() == this.proceedBtn)
            try
            {
                Department department = (Department)this.deptComboBox.getSelectedItem();
                if(department != null)
                {
                    MainFrame mainFrame = new MainFrame(department);
                    this.setVisible(false);
                    mainFrame.setVisible(true);
                }
                else
                    JOptionPane.showMessageDialog(this, "Please select a department or create a new one.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(ClassNotFoundException | IOException | SQLException xcp)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, xcp.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                xcp.printStackTrace(System.err);
            }
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void createNewDeptBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createNewDeptBtnActionPerformed
    {//GEN-HEADEREND:event_createNewDeptBtnActionPerformed
        if(evt.getSource() == this.createNewDeptBtn)
        {
            CreateNewDepartment cnd = new CreateNewDepartment(this, true);
            cnd.setVisible(true);
        }
    }//GEN-LAST:event_createNewDeptBtnActionPerformed

    protected void addNewDepartmentToComboBox(Department d)
    {
        this.deptComboBox.addItem(d);
    }

    private void setDefaultLookAndFeel()
    {
        WindowsSetter.setWindowsLookAndFeel(this);
    }

    private void centralizeWindow()
    {
        WindowsSetter.centralizeWindow(this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewDeptBtn;
    private javax.swing.JComboBox deptComboBox;
    private javax.swing.JLabel deptIconLbl;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JLabel selectDeptLbl;
    private javax.swing.JLabel selectLbl;
    // End of variables declaration//GEN-END:variables

}
