/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyneex.att.venues;

import com.xyneex.att.MainFrame;
import com.xyneex.att.beans.Venue;
import com.xyneex.att.util.WindowsSetter;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Jevison7x
 */
public class AddVenueDialog extends JDialog
{
    private VenuesListDialog venuesListDialog;

    /**
     * Creates new form AddVenueDialog
     */
    public AddVenueDialog(MainFrame parent, VenuesListDialog venuesListDialog)
    {
        super(parent, true);
        this.venuesListDialog = venuesListDialog;
        this.initComponents();
        this.centralizeWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        venueNameLbl = new javax.swing.JLabel();
        venueNameTF = new javax.swing.JTextField();
        internal = new javax.swing.JRadioButton();
        external = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Add_button_inside_black_circle_32.png"))); // NOI18N
        titleLbl.setText("Add Venue");

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Save_Disk_32.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Cancel_button_32.png"))); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelBtnActionPerformed(evt);
            }
        });

        venueNameLbl.setText("Venue Name:");

        buttonGroup.add(internal);
        internal.setText("Internal");

        buttonGroup.add(external);
        external.setText("External");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(venueNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(internal)
                                .addGap(18, 18, 18)
                                .addComponent(external))
                            .addComponent(venueNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, saveBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venueNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internal)
                    .addComponent(external))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelBtn, saveBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveBtnActionPerformed
    {//GEN-HEADEREND:event_saveBtnActionPerformed
        if(evt.getSource() == this.saveBtn)
            if(venueNameTF.getText().equals(""))
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter the name of the venue", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            else if(venueNameTF.getText().length() > 10)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "The venue name is too long, maximum of 10 characters", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            else if(!this.internal.isSelected() && !this.external.isSelected())
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please select internal or external venue", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                String venueName = this.venueNameTF.getText().toUpperCase();
                boolean internalVenue = this.internal.isSelected();
                Venue venue = new Venue();
                venue.setVenueName(venueName);
                venue.setInternal(internalVenue);
                try
                {
                    boolean inserted = VenueDAO.insertVenue(venue);
                    if(inserted)
                    {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, venueName + " was inserted successfully.", "Info", JOptionPane.INFORMATION_MESSAGE);
                        this.venuesListDialog.refreshTable();
                        this.dispose();
                    }
                }
                catch(SQLException xcp)
                {
                    if(xcp instanceof SQLIntegrityConstraintViolationException)
                    {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "This Venue '" + venueName + "' already exists!", "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, xcp.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                        xcp.printStackTrace(System.err);
                    }
                }
            }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelBtnActionPerformed
    {//GEN-HEADEREND:event_cancelBtnActionPerformed
        if(evt.getSource() == this.cancelBtn)
            this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void centralizeWindow()
    {
        WindowsSetter.centralizeWindow(this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton external;
    private javax.swing.JRadioButton internal;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel venueNameLbl;
    private javax.swing.JTextField venueNameTF;
    // End of variables declaration//GEN-END:variables

}
