/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyneex.att.venues;

import com.xyneex.att.MainFrame;
import com.xyneex.att.beans.Venue;
import com.xyneex.att.util.WindowsSetter;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jevison7x
 */
public class VenuesListDialog extends javax.swing.JDialog
{
    private VenueTableModel vtm;

    /**
     * Creates new form VenuesListDialog
     */
    public VenuesListDialog(MainFrame parent, List<Venue> venues)
    {
        super(parent, true);
        this.vtm = new VenueTableModel(venues);
        this.initComponents();
        this.centralizeWindow();
    }

    protected void refreshTable()
    {
        try
        {
            List<Venue> venues = VenueDAO.getAllVenues();
            this.vtm = new VenueTableModel(venues);
            this.venuesTable.setModel(this.vtm);
        }
        catch(Exception xcp)
        {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, xcp.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            xcp.printStackTrace(System.err);
        }
    }

    private void centralizeWindow()
    {
        WindowsSetter.centralizeWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        venuesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Location_pin_32.png"))); // NOI18N
        titleLbl.setText("Venues List");

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Add_button_inside_black_circle_32.png"))); // NOI18N
        addBtn.setText("Add Venue");
        addBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Remove_Circular_Button_32.png"))); // NOI18N
        removeBtn.setText("Remove Venue");
        removeBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                removeBtnActionPerformed(evt);
            }
        });

        venuesTable.setModel(this.vtm);
        scrollPane.setViewportView(venuesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(addBtn)
                                .addGap(192, 192, 192)
                                .addComponent(removeBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPane)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, removeBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addBtnActionPerformed
    {//GEN-HEADEREND:event_addBtnActionPerformed
        if(evt.getSource() == this.addBtn)
        {
            AddVenueDialog avd = new AddVenueDialog((MainFrame)this.getParent(), this);
            avd.setVisible(true);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeBtnActionPerformed
    {//GEN-HEADEREND:event_removeBtnActionPerformed
        if(evt.getSource() == this.removeBtn)
            try
            {
                int selectedRow = this.venuesTable.getSelectedRow();
                String venueName = (String)this.vtm.getValueAt(selectedRow, this.vtm.findColumn(VenueTableModel.VENUE_NAME));
                int q = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the venue " + venueName + "?", "Please Confirm", JOptionPane.YES_NO_OPTION);
                if(q == JOptionPane.YES_OPTION)
                {
                    boolean deleted = VenueDAO.removeVenue(venueName);
                    if(deleted)
                    {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "The venue " + venueName + " has been deleted successfully.", "Info", JOptionPane.INFORMATION_MESSAGE);
                        this.refreshTable();
                    }
                }
            }
            catch(SQLException xcp)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, xcp.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                xcp.printStackTrace(System.err);
            }
            catch(IndexOutOfBoundsException xcp)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please Select a row to delete!", "Cant Delete!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_removeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTable venuesTable;
    // End of variables declaration//GEN-END:variables

}
