/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyneex.att;

import com.xyneex.att.beans.Day;
import com.xyneex.att.beans.Period;
import com.xyneex.att.util.ScheduleClashingException;
import com.xyneex.att.util.WindowsSetter;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Jevison7x
 */
public class SetSeminarPeriodDialog extends javax.swing.JDialog
{

    /**
     * Creates new form SetSeminarPeriodDialog
     */
    public SetSeminarPeriodDialog(MainFrame parent)
    {
        super(parent, true);
        this.initComponents();
        this.centralizeWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleLbl = new javax.swing.JLabel();
        dayCB = new javax.swing.JComboBox(Day.STR_DAYS);
        dayLbl = new javax.swing.JLabel();
        periodLbl = new javax.swing.JLabel();
        periodCB = new javax.swing.JComboBox(Period.SEMINAR_PERIODS);
        fixScheduleBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/xyneex/att/icons/Marketing_Seminar_32.png"))); // NOI18N
        titleLbl.setText("Seminar Period Schedule");

        dayLbl.setText("Day:");

        periodLbl.setText("Period:");

        fixScheduleBtn.setText("Fix Schedule");
        fixScheduleBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fixScheduleBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(periodLbl)
                            .addComponent(dayLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayCB, 0, 116, Short.MAX_VALUE)
                            .addComponent(periodCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(fixScheduleBtn)
                    .addGap(78, 78, 78)
                    .addComponent(cancelBtn)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, fixScheduleBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodLbl)
                    .addComponent(periodCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fixScheduleBtn)
                        .addComponent(cancelBtn))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fixScheduleBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fixScheduleBtnActionPerformed
    {//GEN-HEADEREND:event_fixScheduleBtnActionPerformed
        if(evt.getSource() == this.fixScheduleBtn)
            try
            {
                String strTimePeriod = this.periodCB.getSelectedItem().toString();
                String strDay = this.dayCB.getSelectedItem().toString();
                MainFrame mainFrame = (MainFrame)this.getParent();
                mainFrame.fixSeminarSchedule(strDay, strTimePeriod);
                this.dispose();
            }
            catch(ScheduleClashingException | IllegalArgumentException xcp)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, xcp.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_fixScheduleBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelBtnActionPerformed
    {//GEN-HEADEREND:event_cancelBtnActionPerformed
        if(evt.getSource() == this.cancelBtn)
            this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void centralizeWindow()
    {
        WindowsSetter.centralizeWindow(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox dayCB;
    private javax.swing.JLabel dayLbl;
    private javax.swing.JButton fixScheduleBtn;
    private javax.swing.JComboBox periodCB;
    private javax.swing.JLabel periodLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

}
